/* Generated by tools/cuda_libm_hardcases.cu; do not edit.
 * glibc 2.44, CUDA runtime 13030, NVIDIA GeForce RTX 5090 (sm_120).
 * Inputs where CUDA's double libm rounded to float differs from
 * glibc's; see src/cuda/tmnf_dev_libm.h. */
#ifndef TMNF_LIBM_HARDCASES_H
#define TMNF_LIBM_HARDCASES_H

/* The table is only valid for the glibc that produced the host side
 * and the CUDA toolkit that produced the device side; TmnfCudaVecEnv_Create
 * checks both and the cuda_libm_hardcases test rescans. */
#define TMNF_LIBM_GLIBC_VERSION "2.44"
#define TMNF_LIBM_CUDART_VERSION 13030

enum { TMNF_LIBM_SIN_HARD_COUNT = 0 };
__device__ static const TmnfLibmHardCase1 TMNF_LIBM_SIN_HARD[1] = {
	{ 0, 0 },
};

enum { TMNF_LIBM_COS_HARD_COUNT = 2 };
__device__ static const TmnfLibmHardCase1 TMNF_LIBM_COS_HARD[2] = {
	{ 0x5922aa80u, 0x3f08aebfu },
	{ 0xd922aa80u, 0x3f08aebfu },
};

enum { TMNF_LIBM_EXP_HARD_COUNT = 0 };
__device__ static const TmnfLibmHardCase1 TMNF_LIBM_EXP_HARD[1] = {
	{ 0, 0 },
};

enum { TMNF_LIBM_ATAN2_HARD_COUNT = 1 };
__device__ static const TmnfLibmHardCase2 TMNF_LIBM_ATAN2_HARD[1] = {
	{ 0x3f7ffffcu, 0x3a2e0110u, 0x3fc8fa1bu },
};

#endif
